[2023-10-01 05:58:34,371] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.thrid_task 2021-09-05T00:00:00+00:00 [queued]>
[2023-10-01 05:58:34,453] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.thrid_task 2021-09-05T00:00:00+00:00 [queued]>
[2023-10-01 05:58:34,458] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:58:34,461] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 05:58:34,473] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:58:34,876] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): thrid_task> on 2021-09-05T00:00:00+00:00
[2023-10-01 05:58:35,057] {standard_task_runner.py:52} INFO - Started process 2842 to run task
[2023-10-01 05:58:35,282] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_third_dag_v3', 'thrid_task', '2021-09-05T00:00:00+00:00', '--job-id', '268', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_third_dag.py', '--cfg-path', '/tmp/tmpzfvz_kzn', '--error-file', '/tmp/tmpef5m98gd']
[2023-10-01 05:58:35,673] {standard_task_runner.py:77} INFO - Job 268: Subtask thrid_task
[2023-10-01 05:58:37,326] {logging_mixin.py:104} INFO - Running <TaskInstance: our_third_dag_v3.thrid_task 2021-09-05T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 05:58:38,978] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_third_dag_v3
AIRFLOW_CTX_TASK_ID=thrid_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-05T00:00:00+00:00
[2023-10-01 05:58:39,010] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 05:58:39,020] {bash.py:158} INFO - Running command: echo hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 05:58:39,252] {bash.py:169} INFO - Output:
[2023-10-01 05:58:39,281] {bash.py:173} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 05:58:39,295] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 05:58:39,642] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_third_dag_v3, task_id=thrid_task, execution_date=20210905T000000, start_date=20231001T055834, end_date=20231001T055839
[2023-10-01 05:58:40,842] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 05:58:41,064] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 2842
[2023-10-01 05:58:42,434] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 05:58:42,451] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 05:58:42,878] {process_utils.py:66} INFO - Process psutil.Process(pid=2842, status='terminated', exitcode=1, started='05:58:34') (2842) terminated with exit code 1
