[2023-10-01 10:15:08,687] {logging_mixin.py:104} INFO - Running <TaskInstance: postgres_v2.create_postgres_connection 2021-08-06T00:00:00+00:00 [None]> on host d4ed655215d1
[2023-10-01 10:15:10,320] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=postgres_v2
AIRFLOW_CTX_TASK_ID=create_postgres_connection
AIRFLOW_CTX_EXECUTION_DATE=2021-08-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-06T00:00:00+00:00
[2023-10-01 10:15:10,348] {postgres.py:69} INFO - Executing: create table if not exists dags_run(
        dt  date,
        dag_id character varying,
        primary key (dt,dag_id)
        )
[2023-10-01 10:15:10,538] {base.py:74} INFO - Using connection to: id: posgres_testing. Host: host.docker.internal, Port: 5432, Schema: testing, Login: airflow, Password: XXXXXXXX, extra: None
[2023-10-01 10:15:10,706] {dbapi.py:180} INFO - Running statement: create table if not exists dags_run(
        dt  date,
        dag_id character varying,
        primary key (dt,dag_id)
        ), parameters: None
[2023-10-01 10:15:10,745] {dbapi.py:186} INFO - Rows affected: -1
[2023-10-01 10:15:10,781] {postgres.py:73} INFO - NOTICE:  relation "dags_run" already exists, skipping

[2023-10-01 10:15:11,088] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=postgres_v2, task_id=create_postgres_connection, execution_date=20210806T000000, start_date=20231001T101504, end_date=20231001T101511
[2023-10-01 10:15:13,905] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
