[2023-10-01 05:57:35,093] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.thrid_task 2021-08-29T00:00:00+00:00 [queued]>
[2023-10-01 05:57:36,055] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.thrid_task 2021-08-29T00:00:00+00:00 [queued]>
[2023-10-01 05:57:36,069] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:57:36,076] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 05:57:36,089] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 05:57:36,466] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): thrid_task> on 2021-08-29T00:00:00+00:00
[2023-10-01 05:57:36,593] {standard_task_runner.py:52} INFO - Started process 2729 to run task
[2023-10-01 05:57:36,756] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_third_dag_v3', 'thrid_task', '2021-08-29T00:00:00+00:00', '--job-id', '246', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_third_dag.py', '--cfg-path', '/tmp/tmpkgijni2o', '--error-file', '/tmp/tmp25b0p1pj']
[2023-10-01 05:57:36,928] {standard_task_runner.py:77} INFO - Job 246: Subtask thrid_task
[2023-10-01 05:57:38,472] {logging_mixin.py:104} INFO - Running <TaskInstance: our_third_dag_v3.thrid_task 2021-08-29T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 05:57:39,867] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_third_dag_v3
AIRFLOW_CTX_TASK_ID=thrid_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-29T00:00:00+00:00
[2023-10-01 05:57:39,881] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 05:57:39,906] {bash.py:158} INFO - Running command: echo hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 05:57:40,102] {bash.py:169} INFO - Output:
[2023-10-01 05:57:40,185] {bash.py:173} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-10-01 05:57:40,189] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 05:57:40,349] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_third_dag_v3, task_id=thrid_task, execution_date=20210829T000000, start_date=20231001T055735, end_date=20231001T055740
[2023-10-01 05:57:42,469] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 05:57:42,601] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 2729
[2023-10-01 05:57:43,083] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 05:57:43,086] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 05:57:43,469] {process_utils.py:66} INFO - Process psutil.Process(pid=2729, status='terminated', exitcode=1, started='05:57:35') (2729) terminated with exit code 1
