[2023-10-01 06:02:52,669] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.second_task 2021-10-24T00:00:00+00:00 [queued]>
[2023-10-01 06:02:53,001] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_third_dag_v3.second_task 2021-10-24T00:00:00+00:00 [queued]>
[2023-10-01 06:02:53,008] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:02:53,027] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:02:53,029] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:02:53,146] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2021-10-24T00:00:00+00:00
[2023-10-01 06:02:53,218] {standard_task_runner.py:52} INFO - Started process 3525 to run task
[2023-10-01 06:02:53,300] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_third_dag_v3', 'second_task', '2021-10-24T00:00:00+00:00', '--job-id', '415', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_third_dag.py', '--cfg-path', '/tmp/tmp13oznu12', '--error-file', '/tmp/tmpapen4gda']
[2023-10-01 06:02:53,324] {standard_task_runner.py:77} INFO - Job 415: Subtask second_task
[2023-10-01 06:02:54,329] {logging_mixin.py:104} INFO - Running <TaskInstance: our_third_dag_v3.second_task 2021-10-24T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:02:55,016] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_third_dag_v3
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-10-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-24T00:00:00+00:00
[2023-10-01 06:02:55,027] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:02:55,032] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2023-10-01 06:02:55,328] {bash.py:169} INFO - Output:
[2023-10-01 06:02:55,386] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2023-10-01 06:02:55,409] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:03:06,652] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_third_dag_v3, task_id=second_task, execution_date=20211024T000000, start_date=20231001T060252, end_date=20231001T060306
[2023-10-01 06:03:16,848] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 06:03:17,220] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 3525
[2023-10-01 06:03:20,703] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 06:03:21,023] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-10-01 06:03:26,630] {process_utils.py:66} INFO - Process psutil.Process(pid=3525, status='terminated', exitcode=1, started='06:02:52') (3525) terminated with exit code 1
