[2023-10-01 10:04:36,078] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v1.insert_into_table 2021-09-04T00:00:00+00:00 [queued]>
[2023-10-01 10:04:36,207] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v1.insert_into_table 2021-09-04T00:00:00+00:00 [queued]>
[2023-10-01 10:04:36,210] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 10:04:36,211] {taskinstance.py:1043} INFO - Starting attempt 3 of 6
[2023-10-01 10:04:36,217] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 10:04:36,350] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2021-09-04T00:00:00+00:00
[2023-10-01 10:04:36,396] {standard_task_runner.py:52} INFO - Started process 45399 to run task
[2023-10-01 10:04:36,421] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_v1', 'insert_into_table', '2021-09-04T00:00:00+00:00', '--job-id', '2670', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/1_postgresql.py', '--cfg-path', '/tmp/tmpcmp3dava', '--error-file', '/tmp/tmpp0sv_ooq']
[2023-10-01 10:04:36,464] {standard_task_runner.py:77} INFO - Job 2670: Subtask insert_into_table
[2023-10-01 10:04:36,879] {logging_mixin.py:104} INFO - Running <TaskInstance: postgres_v1.insert_into_table 2021-09-04T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 10:04:37,257] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=postgres_v1
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2021-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-04T00:00:00+00:00
[2023-10-01 10:04:37,268] {postgres.py:69} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2021-09-04', 'postgres_v1')
        
[2023-10-01 10:04:37,327] {base.py:74} INFO - Using connection to: id: posgres_testing. Host: host.docker.internal, Port: 5432, Schema: testing, Login: airflow, Password: XXXXXXXX, extra: None
[2023-10-01 10:04:37,370] {dbapi.py:180} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2021-09-04', 'postgres_v1')
        , parameters: None
[2023-10-01 10:04:37,388] {taskinstance.py:1455} ERROR - relation "dag_runs" does not exist
LINE 2:             insert into dag_runs (dt, dag_id) values ('2021-...
                                ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "dag_runs" does not exist
LINE 2:             insert into dag_runs (dt, dag_id) values ('2021-...
                                ^

[2023-10-01 10:04:37,401] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_v1, task_id=insert_into_table, execution_date=20210904T000000, start_date=20231001T100436, end_date=20231001T100437
[2023-10-01 10:04:37,635] {local_task_job.py:146} INFO - Task exited with return code 1
