[2023-10-01 09:59:39,025] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v1.create_postgres_connection 2021-09-02T00:00:00+00:00 [queued]>
[2023-10-01 09:59:39,224] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: postgres_v1.create_postgres_connection 2021-09-02T00:00:00+00:00 [queued]>
[2023-10-01 09:59:39,226] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 09:59:39,228] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 09:59:39,230] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 09:59:39,301] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_postgres_connection> on 2021-09-02T00:00:00+00:00
[2023-10-01 09:59:39,402] {standard_task_runner.py:52} INFO - Started process 44163 to run task
[2023-10-01 09:59:39,800] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_v1', 'create_postgres_connection', '2021-09-02T00:00:00+00:00', '--job-id', '2628', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/1_postgresql.py', '--cfg-path', '/tmp/tmp5js060vj', '--error-file', '/tmp/tmpsm2jcrm7']
[2023-10-01 09:59:39,886] {standard_task_runner.py:77} INFO - Job 2628: Subtask create_postgres_connection
[2023-10-01 09:59:41,637] {logging_mixin.py:104} INFO - Running <TaskInstance: postgres_v1.create_postgres_connection 2021-09-02T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 09:59:43,705] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=postgres_v1
AIRFLOW_CTX_TASK_ID=create_postgres_connection
AIRFLOW_CTX_EXECUTION_DATE=2021-09-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-02T00:00:00+00:00
[2023-10-01 09:59:43,825] {postgres.py:69} INFO - Executing: create table if not exists dags_run(
        dt  date,
        dag_id character varying,
        primary key (dt,dag_id)
        )
[2023-10-01 09:59:44,418] {base.py:74} INFO - Using connection to: id: posgres_testing. Host: host.docker.internal, Port: 5432, Schema: testing, Login: airflow, Password: XXXXXXXX, extra: None
[2023-10-01 09:59:44,838] {dbapi.py:180} INFO - Running statement: create table if not exists dags_run(
        dt  date,
        dag_id character varying,
        primary key (dt,dag_id)
        ), parameters: None
[2023-10-01 09:59:44,864] {dbapi.py:186} INFO - Rows affected: -1
[2023-10-01 09:59:44,877] {postgres.py:73} INFO - NOTICE:  relation "dags_run" already exists, skipping

[2023-10-01 09:59:45,097] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=postgres_v1, task_id=create_postgres_connection, execution_date=20210902T000000, start_date=20231001T095939, end_date=20231001T095945
[2023-10-01 09:59:45,436] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-01 09:59:45,652] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 44163
[2023-10-01 09:59:49,620] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-01 09:59:51,543] {process_utils.py:66} INFO - Process psutil.Process(pid=44163, status='terminated', exitcode=1, started='09:59:39') (44163) terminated with exit code 1
