[2023-10-01 06:17:22,816] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.second_task 2021-11-28T00:00:00+00:00 [queued]>
[2023-10-01 06:17:23,114] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_fourth_dag_v4.second_task 2021-11-28T00:00:00+00:00 [queued]>
[2023-10-01 06:17:23,116] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:17:23,118] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2023-10-01 06:17:23,139] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-10-01 06:17:23,387] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2021-11-28T00:00:00+00:00
[2023-10-01 06:17:24,650] {standard_task_runner.py:52} INFO - Started process 5749 to run task
[2023-10-01 06:17:24,915] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_fourth_dag_v4', 'second_task', '2021-11-28T00:00:00+00:00', '--job-id', '797', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_fourth_dag.py', '--cfg-path', '/tmp/tmpwot7e86g', '--error-file', '/tmp/tmp2pkd9hxs']
[2023-10-01 06:17:25,217] {standard_task_runner.py:77} INFO - Job 797: Subtask second_task
[2023-10-01 06:17:26,285] {logging_mixin.py:104} INFO - Running <TaskInstance: our_fourth_dag_v4.second_task 2021-11-28T00:00:00+00:00 [running]> on host d4ed655215d1
[2023-10-01 06:17:27,035] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=svastikkka
AIRFLOW_CTX_DAG_ID=our_fourth_dag_v4
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-28T00:00:00+00:00
[2023-10-01 06:17:27,041] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-10-01 06:17:27,046] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2023-10-01 06:17:27,332] {bash.py:169} INFO - Output:
[2023-10-01 06:17:27,411] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2023-10-01 06:17:27,413] {bash.py:177} INFO - Command exited with return code 0
[2023-10-01 06:17:27,864] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_fourth_dag_v4, task_id=second_task, execution_date=20211128T000000, start_date=20231001T061722, end_date=20231001T061727
[2023-10-01 06:17:28,493] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01 06:17:28,822] {local_task_job.py:146} INFO - Task exited with return code 0
